name: ms-annotation-qc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas>=1.5.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - numpy>=1.23.0
  - scipy>=1.9.0
  - pip
  - pip:
    - pyteomics>=4.5.0
    - msbuddy
